// ==========================================
// ALADINDOTCOM - ADMIN PANEL
// FINAL VERSION
// ==========================================

let isEditing = false;

auth.onAuthStateChanged(user => {
  if (!user || user.email !== 'purevalue185@gmail.com') { alert('Access denied!'); location.href = 'index.html'; return; }
  document.getElementById('adminEmail').textContent = '👑 ' + user.email;
  updateStats(); renderProductsTable();
});

function addSpecRow(){const c=document.getElementById('specsContainer');const r=document.createElement('div');r.className='dynamic-row';r.innerHTML='<input type="text" placeholder="Name (e.g. Brand)" class="spec-key"><input type="text" placeholder="Value (e.g. AudioTech)" class="spec-value"><button type="button" class="btn-remove" onclick="removeRow(this)"><i class="fas fa-times"></i></button>';c.appendChild(r);}
function addPricingRow(){const c=document.getElementById('pricingContainer');const r=document.createElement('div');r.className='dynamic-row';r.innerHTML='<input type="text" placeholder="Quantity (e.g. 50-100)" class="price-qty"><input type="text" placeholder="Price (e.g. $6.80/unit)" class="price-value"><button type="button" class="btn-remove" onclick="removeRow(this)"><i class="fas fa-times"></i></button>';c.appendChild(r);}
function removeRow(btn){const r=btn.parentElement;const c=r.parentElement;if(c.children.length>1)r.remove();}
function getSpecs(){const s={};document.querySelectorAll('#specsContainer .dynamic-row').forEach(r=>{const k=r.querySelector('.spec-key').value.trim();const v=r.querySelector('.spec-value').value.trim();if(k&&v)s[k]=v;});return s;}
function getPrices(){const p=[];document.querySelectorAll('#pricingContainer .dynamic-row').forEach(r=>{const q=r.querySelector('.price-qty').value.trim();const pr=r.querySelector('.price-value').value.trim();if(q&&pr)p.push({qty:q,price:pr});});return p;}
function fillSpecs(specs){const c=document.getElementById('specsContainer');c.innerHTML='';if(Object.keys(specs).length===0){addSpecRow();return;}Object.entries(specs).forEach(([k,v])=>{const r=document.createElement('div');r.className='dynamic-row';r.innerHTML='<input type="text" class="spec-key" value="'+k+'"><input type="text" class="spec-value" value="'+v+'"><button type="button" class="btn-remove" onclick="removeRow(this)"><i class="fas fa-times"></i></button>';c.appendChild(r);});}
function fillPrices(prices){const c=document.getElementById('pricingContainer');c.innerHTML='';if(prices.length===0){addPricingRow();return;}prices.forEach(p=>{const r=document.createElement('div');r.className='dynamic-row';r.innerHTML='<input type="text" class="price-qty" value="'+p.qty+'"><input type="text" class="price-value" value="'+p.price+'"><button type="button" class="btn-remove" onclick="removeRow(this)"><i class="fas fa-times"></i></button>';c.appendChild(r);});}

document.querySelectorAll('.nav-item[data-page]').forEach(item=>{item.addEventListener('click',function(e){e.preventDefault();const p=this.dataset.page;document.querySelectorAll('.page-content').forEach(pg=>pg.classList.remove('active'));document.getElementById(p+'-page').classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));this.classList.add('active');if(p==='products')renderProductsTable();if(p==='dashboard')updateStats();if(p==='orders')renderOrders();if(p==='inquiries')renderInquiries();if(p==='add-product')resetForm();});});

function showProducts(){document.querySelectorAll('.page-content').forEach(p=>p.classList.remove('active'));document.getElementById('products-page').classList.add('active');renderProductsTable();}
function showAddProduct(){document.querySelectorAll('.page-content').forEach(p=>p.classList.remove('active'));document.getElementById('add-product-page').classList.add('active');resetForm();}

function renderProductsTable(){database.ref('products').once('value').then(s=>{const d=s.val();const p=d?Object.values(d).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)):[];document.getElementById('productsTableBody').innerHTML=p.length===0?'<tr><td colspan="6">No products</td></tr>':p.map(pr=>'<tr><td>'+(pr.img&&pr.img.startsWith('http')?'<img src="'+pr.img+'" style="width:50px;height:50px;object-fit:cover;border-radius:5px;">':'<span style="font-size:2rem;">'+(pr.img||'📦')+'</span>')+'</td><td><strong>'+pr.title+'</strong></td><td>'+pr.category+'</td><td>'+(pr.moq||'N/A')+'</td><td>'+(pr.price||'N/A')+'</td><td><button class="btn btn-primary btn-sm" onclick="editProduct(\''+pr.id+'\')" style="padding:0.3rem 0.8rem;font-size:0.8rem;">Edit</button> <button class="btn btn-outline btn-sm" onclick="deleteProduct(\''+pr.id+'\')" style="padding:0.3rem 0.8rem;font-size:0.8rem;color:red;">Del</button></td></tr>').join('');});}

function editProduct(id){database.ref('products/'+id).once('value').then(s=>{const p=s.val();if(!p)return;isEditing=true;document.getElementById('formTitle').textContent='Edit Product';document.getElementById('productId').value=p.id;document.getElementById('prodTitle').value=p.title||'';document.getElementById('prodCategory').value=p.category||'';document.getElementById('prodImageUrl').value=(p.img&&p.img.startsWith('http'))?p.img:'';document.getElementById('prodImg').value=(p.img&&!p.img.startsWith('http'))?p.img:'';document.getElementById('prodMoq').value=p.moq||'';document.getElementById('prodPrice').value=p.price||'';document.getElementById('prodSupplier').value=p.supplier||'';document.getElementById('prodShipping').value=p.shipping||'';document.getElementById('prodRating').value=p.rating||4.5;document.getElementById('prodReviews').value=p.reviews||0;document.getElementById('prodDesc').value=p.desc||'';document.getElementById('prodImages').value=(p.images||[]).join(', ');fillSpecs(p.specifications||{});fillPrices(p.bulkPrices||[]);showAddProduct();});}
function deleteProduct(id){if(confirm('Delete?')){database.ref('products/'+id).remove().then(()=>{renderProductsTable();updateStats();});}}
function resetForm(){isEditing=false;document.getElementById('formTitle').textContent='Add New Product';document.getElementById('productForm').reset();document.getElementById('productId').value='';fillSpecs({});fillPrices([]);}

document.getElementById('productForm').addEventListener('submit',function(e){e.preventDefault();const imgUrl=document.getElementById('prodImageUrl').value.trim();const emoji=document.getElementById('prodImg').value.trim();const pid=document.getElementById('productId').value;const product={id:pid?parseInt(pid):Date.now(),title:document.getElementById('prodTitle').value,category:document.getElementById('prodCategory').value,img:imgUrl||emoji||'📦',moq:document.getElementById('prodMoq').value,price:document.getElementById('prodPrice').value,supplier:document.getElementById('prodSupplier').value,shipping:document.getElementById('prodShipping').value,rating:parseFloat(document.getElementById('prodRating').value)||4.5,reviews:parseInt(document.getElementById('prodReviews').value)||0,desc:document.getElementById('prodDesc').value,images:document.getElementById('prodImages').value.split(',').map(i=>i.trim()).filter(i=>i),specifications:getSpecs(),bulkPrices:getPrices(),updatedAt:firebase.database.ServerValue.TIMESTAMP};if(!isEditing)product.createdAt=firebase.database.ServerValue.TIMESTAMP;database.ref('products/'+product.id).set(product).then(()=>{alert(isEditing?'Updated!':'Added!');resetForm();showProducts();}).catch(e=>alert('Error: '+e.message));});

function renderOrders(){database.ref('orders').orderByChild('createdAt').limitToLast(50).once('value').then(s=>{const d=s.val();const o=d?Object.entries(d).map(([k,v])=>({id:k,...v})).reverse():[];document.getElementById('ordersTableBody').innerHTML=o.length===0?'<tr><td colspan="5">No orders</td></tr>':o.map(or=>'<tr><td>'+(or.createdAt?new Date(or.createdAt).toLocaleDateString():'')+'</td><td>'+(or.productTitle||'')+'</td><td>'+(or.userName||'Guest')+'</td><td>'+(or.userEmail||'')+'</td><td>'+or.status+'</td></tr>').join('');});}
function renderInquiries(){database.ref('inquiries').orderByChild('createdAt').limitToLast(50).once('value').then(s=>{const d=s.val();const i=d?Object.entries(d).map(([k,v])=>({id:k,...v})).reverse():[];document.getElementById('inquiriesTableBody').innerHTML=i.length===0?'<tr><td colspan="4">No inquiries</td></tr>':i.map(inq=>'<tr><td>'+(inq.createdAt?new Date(inq.createdAt).toLocaleDateString():'')+'</td><td>'+(inq.name||'')+'</td><td>'+(inq.email||'')+'</td><td>'+((inq.message||'').substring(0,50))+'...</td></tr>').join('');});}
function updateStats(){database.ref('products').once('value').then(s=>{document.getElementById('totalProducts').textContent=s.exists()?Object.keys(s.val()).length:0;});database.ref('orders').once('value').then(s=>{document.getElementById('totalOrders').textContent=s.exists()?Object.keys(s.val()).length:0;});database.ref('inquiries').once('value').then(s=>{document.getElementById('totalInquiries').textContent=s.exists()?Object.keys(s.val()).length:0;});}

window.showProducts=showProducts;window.showAddProduct=showAddProduct;
window.editProduct=editProduct;window.deleteProduct=deleteProduct;
window.addSpecRow=addSpecRow;window.addPricingRow=addPricingRow;window.removeRow=removeRow;
document.addEventListener('DOMContentLoaded',()=>{updateStats();renderProductsTable();});
